### ISSUE TITLE
RegionAllocator:  Empty matrix?

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#17]
Two related issues:  First, using a RegionAllocator with eval seems to require passing a pointer instead of a
copy.  

Secondly, the following code results in x2 being an empty matrix.

```
import scid.matvec, std.stdio, scid.internal.regionallocator;

void main(string[] args) {
    auto x = Matrix!double([[1.0, 2, 3], [4.0, 5, 6], [7.0, 8, 9]]);
    auto alloc = newRegionAllocator();
    auto x2 = eval(x.t * x, &alloc);
    writeln(x2.pretty);
}
```

If I change &alloc to alloc, I get:

C:\code\test.d(6): Error: template scid.ops.eval.eval(T) if (isLeafExpression!(T)) does not match any function template declaration
C:\code\test.d(6): Error: template scid.ops.eval.eval(T) if (isLeafExpression!(T)) cannot deduce template function from argument types !()(Expression!(op,Expression!(op,BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))),RegionAllocator)

**Comment by cristicbz** [comment]
I know why the empty matrix happens, I'll commit the fix. About the fact that eval takes a pointer, it was a workaround for a problem I thought was my fault, but now I realize that it's probably RegionAllocator.
Try removing Allocator\* from the definitions of eval() and the c-tors of ExternalArray and ExternalMatrix (scid.ops.eval and scid.storage.external, respectively) and pass alloc rather than &alloc. I get a "Range violation error." in regionallocator.d@319.
I'll try to isolate it and I'll post the issue on the RegionAllocator page.
