### ISSUE TITLE
64-bit support

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#23]
SciD doesn't compile in 64-bit mode due to various size_t -> int conversion issues.  If you don't have a 64-bit system conveniently available, or are busy with higher-priority issues, I'll take care of this one in the next few days, since it's pretty trivial to fix.

**Comment by cristicbz** [comment]
I am actually running a 64bit system, but 32bit dmd, because there is
no prepackaged Win64 build. Can I compile it with dmc in 64 bit mode?

---

Cristi Cobzarenco
BSc in Artificial Intelligence and Computer Science
University of Edinburgh
Profile: http://www.google.com/profiles/cristi.cobzarenco

On 3 August 2011 20:07, dsimcha
reply@reply.github.com
wrote:

**Comment by dsimcha** [comment]
Cristi,

DMD/DMC doesn't work in 64-bit mode in Windows.  It does in Linux and
FreeBSD.  I ran into this on my work Linux box.  There's no _mature_ 64-bit
Windows D compiler.  If you don't have 64-bit Linux/FreeBSD conveniently
available, don't worry about it, I'll fix this one.

--Dave

**Comment by dsimcha** [comment]
Fixed.  For future reference, please remember that, in D, integer narrowing conversions are not implicit.  BLAS/LAPACK uses int (32-bit) for all array lengths, even on 64-bit systems.  This is silly but beyond our control.  I changed your wrappers and naive functions to use size_t (machine word size) for all array lengths and convert them to int when passing them to BLAS/LAPACK.  This was the best way to do it, as it had the least possible ripple effects.

**Comment by cristicbz** [comment]
Sounds great, thanks! I'll make sure to keep that in mind from now on.
I guess we could make version(LargeMatrices) that checks at runtime
whether sizes are greater than 2^31 and if they are it calls naive
functions. After all, a 50,000x50,000 matrix is already greater than
that and it would be nice to support it on 64bit systems. Although
ideally we would provide functions that call BLAS functions on blocks,
because the difference between naive implementations and BLAS calls
will be huge at those sizes.

---

Cristi Cobzarenco
BSc in Artificial Intelligence and Computer Science
University of Edinburgh
Profile: http://www.google.com/profiles/cristi.cobzarenco

On 4 August 2011 03:05, dsimcha
reply@reply.github.com
wrote:

**Comment by dsimcha** [comment]
```
On 8/3/2011 9:14 PM, cristicbz wrote:

  Sounds great, thanks! I'll make sure to keep that in mind from now on.
```

I guess we could make version(LargeMatrices) that checks at runtime
whether sizes are greater than 2^31 and if they are it calls naive
functions. After all, a 50,000x50,000 matrix is already greater than
that and it would be nice to support it on 64bit systems. Although
ideally we would provide functions that call BLAS functions on blocks,
because the difference between naive implementations and BLAS calls
will be huge at those sizes.

```
I think that dealing with a corner case like this is an extremely
low priority.  While I've worked with a roughly 54,000x32,000 matrix
before, some of the operations on it took on the order of a week to
execute, parallelized across 24 cores.  If you are going to do it,
however, I don't think you need a special version.  The extra checks
would probably be cheap enough to just leave them in all the time.
```
