### ISSUE TITLE
Invalid multiplication between ColumnVector and Matrix

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#51]
This code is rejected by SciD even though it makes mathematical sense if mat is treated as if it were a row vector:

```
import scid.matvec, std.stdio;

void main() {
    auto vec = Vector!double([1, 2, 3]);
    auto mat = Matrix!double(1, 3);
    auto ret = eval(vec * mat);
}
```

**Comment by cristicbz** [comment]
Hmmm, this actually somewhat complicated to fix, but it is possible. vec \* mat.row(0) is not going to work either because column-row multiplication isn't supported yet.
If you _really_ need a workaround doing externalMatrixView( 1, vec.data[ 0 .. vec.length ] ) \* mat should work for now. I know it's ugly, but if you really want the operation to get performed, that will work.

**Comment by dsimcha** [comment]
No hurry/workaround needed.  I ran into this one writing a tiny test program
w/ SciD that took about 2 minutes to rewrite in Octave.  The only reason I
used SciD for it in the first place was eating my own dogfood/bug hunting.

**Comment by dsimcha** [comment]
Actually, silly question:  Since your rewriting-as-externalMatrixView trick definitely works (I ended up using it after all), why not just implement column vector-matrix multiplication that way if there's no easier/better way?  (Even if there's some important optimization opportunity I'm missing, you could use this rewriting as the fallback routine.)

**Comment by dsimcha** [comment]
Fixed by Pull Request 71.
