### ISSUE TITLE
regionallocator.d causes build fail

### ISSUE THREAD

**Issue by MaksimZh** [cristicbz/scid#57]
The library fails to build because of the following errors:

regionallocator.d(289): Error: pure nested function 'nLargeObjects' cannot access mutable data 'i'
regionallocator.d(295): Error: pure nested function 'nExtraSegments' cannot access mutable data 'i'
regionallocator.d(949): Error: cannot evaluate isPowerOf2(16LU) at compile time
regionallocator.d(949): Error: static assert  (isPowerOf2(16LU)) is not evaluatable at compile time

OS: Linux
Platform: x64
Compiler: DMD64 D Compiler v2.054

**Comment by dsimcha** [comment]
Hmm, I think I noticed that with stock 2.054.  I've been using Git head builds (I think Cristi's been doing the same) and it works fine on these.  I'm not sure if this is even worth fixing because SciD is so horribly broken for other reasons on stock 2.054 anyhow, for reasons that are fixed on Git head.

**Comment by MaksimZh** [comment]
Thank you!
I've installed dmd from github sources and now everything works.
