### ISSUE TITLE
General matrices and vectors

### ISSUE THREAD

**Issue by MaksimZh** [cristicbz/scid#60]
Currently SciD does not support matrices and vectors for types that are not accepted by BLAS functions (and also types like Complex!double though they are compatible with built-in complex types).

If I see it right the code depends on BLAS only on the level of storages. In this case linear algebra functionality can be generalized to arbitrary types of matrix/vector elements without serious changes in matrix, vector and expression templates.

In any case there could be something like the following subdivision:
1.  The most general case: elements of a linear space.
   The elements of matrices and vectors can be added and multiplied by scalars.
   For such matrices and vectors the operations allowed will be: addition, subtraction, multiplying by scalar, transposing and conjugation.
2.  Elements of an algebra.
   The elements of matrices and vectors can be added, multiplied by scalars and multiplied by each other.
   Multiplication of matrices and vectors will be allowed for such types. A good example is a matrix of matrices. 
3.  Scalar types.
   All linear algebra operations will be allowed and will use BLAS internally. LAPACK operations will be allowed.

Within this approach a Hermitian matrix can be created for any type that has ".conj" property. If matrix elements are some operators in Hilbert space ".conj" should be Hermitian conjugation.

By the way, the following operations should be distinguished:
-  Transposing
-  Complex conjugation
-  Hermitian conjugation

Currently in SciD Hermitian conjugation is called transposing for vectors and matrices. Is it usual terminology in English?

May be all this sound too abstract, but I need most of this functionality for real problems concerning quantum mechanics.

In my opinion SciD should be oriented to this abstraction. D templates look most suitable for such things.

I will be glad to help implement this.

**Comment by cristicbz** [comment]
### Comments
- The reason Complex!\* is not supported was the time constraint of GSoC, it would be very easy to add it.
  BLAS is only used at storage level, yes.
- Non-BLAS types are (sort of) supported already. D's 'real' type for example works with matrices - this is because SciD provides a naive implementation on most BLAS operations. The naive implementation gets used whenever BLAS doesn't work on the particular type.
- Theoretically Matrix & Vector types should already work on any type that satisfies the isScalar concept defined in scid.common.storagetraits. Have you tried using something else that didn't work? Note that arbitrary complex types will not work, but any real-number-like type should work.
- SciD does consider hermitian-transposing to be transposing on complex-valued matrices - we discussed about this near the beginning of the project and we decided that the (non-hermitian) transpose of a complex-valued matrix would be useless. MATLAB's transpose operator also performs hermitian transpose by default. If there is a use case, this should certainly be implemented - but it's not very easy to do as it will have to tie in with the expression templates as well as with the eval\* routines
- Simply conjugating all the elements in a matrix is definitely something that was overlooked. This should also certrainly get implemented.

### What needs to be done
1. Fix any existing (if any) problems that SciD has with working with custom scalar types.
2. Finish naive implementations for all the used BLAS functions. (not difficult, but laborious)
3. Add support for custom complex types. (medium difficulty)
4. Add support for conjugating and hermitian transpose. (pretty hard to do properly, medium to get inefficient version working)

### Practicalities
- I feel very bad about pushing this further and further, but I am extremely busy at the moment and I cannot possibly dedicate any time to SciD right now. The soonest I'll get any time off to work on SciD will probably be in December.
- As the code suffers from a severe lack of documentation (which is a result of the tight time schedule is was written under) I understand that it is difficult to contribute to the existing code base.
- If you do, however, decide to work on this I will be more than happy to answer any questions you have about the design of SciD, provide you with workarounds and explanations of the design decisions I had to make etc. You can email me directly at cristi.cobzarenco.no.spam at gmail dot com, or post stuff here, I'll try to answer promptly and in detail.

**Comment by MaksimZh** [comment]
Thank you for the reply.

Scalars (types that pass isScalar test) has multiplication and division operators. This restriction is too strong if one need only liner operations with matrices and vectors (addition, subtraction, multiplication by scalars and conjugation).

In fact right now I work with quadratic forms. Multiplication or division of them produces another type of object that I don't need.

Currently SciD tries to implement all the functionality for any type and produces errors if some operations are not supported. It will be better if it provide maximal amount of functionality and skip the operations that can not be performed.

As for transposing operation... It looks like Hermitian conjugation is the only operation that have physical sense. It is the natural generalization of complex conjugation. Hence matrix/vector should have a synonym of "Transposed" property called "conj". Pure transposing or conjugation are quite exotic and their implementation can wait.

I really want to work on this project but analysis of the code without understanding the main ideas would take too much time. Could you please explain the main points of the library design? You can e-mail me at maximzms at gmail dot com. 

I think in any case we should prepare some public documents explaining the library structure to help new contributors enter the project.

**Comment by MaksimZh** [comment]
Since now we are about to [redesign the library](https://github.com/cristicbz/scid/wiki/Draft-GSoC-2012-Proposal) this issue can be considered solved.
I'd suggest discuss new design [here](https://github.com/kyllingstad/scid/issues/3).
