### ISSUE TITLE
Build failure with DMD 2.056

### ISSUE THREAD

**Issue by ghost** [cristicbz/scid#66]
Hi,

I just downloaded the latest version to try out SciD. The most recent change seems to be in this fork (on Nov 3), so I'm reporting the bug here, but it also exists in kyllingstad / scid repo.  The build errors are:

build.d(188): Error: alias std.file.isdir is deprecated
build.d(209): Error: alias std.file.isfile is deprecated

This happens with DMD 2.056, so just thought of reporting. Replacing isdir( ) with isDir( )  and similarly isfile( ) with isFile( ) solves the issue.

**Comment by dsimcha** [comment]
Thanks for the report.  I'm aware of this issue, but I haven't fixed it because rewriting the build system from scratch should be a todo and in the mean time build.d works fine if compiled with the -d flag.  The current build system lacks support for such basic things as deciding what architecture (32- or 64-bit) to compile for, deciding what mode (debug/release), handling different compilers (GDC/LDC) and is extremely unconventional.  

On the other hand, I know nothing about proper build systems and almost always build my stuff from either ad-hoc shell scripts or from CodeBlocks.  If anyone wants to tackle improving this, it would be greatly appreciated.

**Comment by ghost** [comment]
Well, I'm very familiar with Makefiles and autoconf tools but I'm new to D. I know the basic compiler options of DMD and GDC though, so I can try to write a build system, if it doesn't take too much of my time.

**Comment by dsimcha** [comment]
Fixed by Pull Request # 70.
