### ISSUE TITLE
Symmetric Matrix C'tor Broken

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#9]
Looks like it's just some old cruft from a different design.

import scid.matvec;

void main() {
    auto m = SymmetricMatrix!double([[1.0, 2, 3], [4.0, 5, 6], [7.0, 8, 9]]);
}

Error message:

scid\matrix.d(114): Error: function scid.storage.symmetric.SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder).SymmetricArrayAdapter.resize (uint size) is not callable using argument types (uint,uint,void*)
D:\customd\scid\matrix.d(114): Error: expected 1 arguments, not 3 for non-variadic function type void(uint size)

**Comment by dsimcha** [comment]
BTW, I know the arguments I passed in aren't symmetric.  This is on purpose.  I was curious what happens in this case.

**Comment by cristicbz** [comment]
Fixed it. It simply ignores the arguments in the lower/upper half of the matrix now, so passing non-symmetric arguments will be quietly ignored - this is good since you might want to pass the upper/lower half of a matrix that you need for something else. This also means you can pass a triangular matrix ( [[1,2,3],[4,5],[6]] ) as well as a normal one. There's also a ctor that simply takes a list [1.,2.,3.,4.,5.,6.] and arranges the elements base on upper/lower and row/column-major.
